python api_usage/crop_apd_by_sdk.py --batch_idx 0
python api_usage/crop_apd_by_sdk.py --batch_idx 1
python api_usage/crop_apd_by_sdk.py --batch_idx 2
python api_usage/crop_apd_by_sdk.py --batch_idx 3
python api_usage/crop_apd_by_sdk.py --batch_idx 4
python api_usage/crop_apd_by_sdk.py --batch_idx 5
python api_usage/crop_apd_by_sdk.py --batch_idx 6
python api_usage/crop_apd_by_sdk.py --batch_idx 7
python api_usage/crop_apd_by_sdk.py --batch_idx 8
python api_usage/crop_apd_by_sdk.py --batch_idx 9
